# Configuración para el despliegue en producción
[build]
  command = "npm run build"
  publish = "dist"

# Variables de entorno para el contexto de producción
[context.production.environment]
  NODE_VERSION = "18"
